name: Build

on:
  push:
    # Always build when there are new commits to master
    branches:
      - master
    # Always build release-tags
    tags:
      - 'releases/**'
  # Always build pull requests
  pull_request:
    branches:
      - '**'

jobs:
  win32:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: dotnet build
    - name: test
      run: dotnet test
